export const UPDATE_COLLECTIONS = "UPDATE_COLLECTIONS";

export const FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START";

export const FETCH_COLLECTIONS_SUCESS = "FETCH_COLLECTIONS_SUCESS";

export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE";