
const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
const ADD_ITEM = "ADD_ITEM"; 
const CLEAR_ITEM_FROM_CART ="CLEAR_ITEM_FROM_CART";
const REMOVE_ITEM = "REMOVE_ITEM";

export { TOGGLE_CART_HIDDEN, ADD_ITEM, CLEAR_ITEM_FROM_CART, REMOVE_ITEM };